### ISSUE TITLE
Failed link to north west of England restrictions 

### ISSUE THREAD

**Issue by AndyCoo71** [dracos/local-lockdown-lookup#1]
After entering a Salford postcode, the correct north west of England restrictions Link is found, but when I click on the link, I get page not found.

**Steps to reproduce**
Open https://dracos.co.uk/made/local-lockdown-lookup/
Enter postcode M27 5DA
Click ‘Look up’
Salford City Council is correctly recognised including the link to the restrictions info site:
_Salford City Council is in a local lockdown.
Source and more info: https://www.gov.uk/guidance/north-west-of-england-local-restrictions-what-you-can-and-cannot-do._
Click on the gov.uk link.

**Expected behaviour**
Gov.uk site is correctly displayed.

**Actual behaviour**
Link actually followed is https://dracos.co.uk/%3Cwbr%3E/%3Cwbr%3Ewww.gov.uk/%3Cwbr%3Eguidance/%3Cwbr%3Enorth-west-of-england-local-restrictions-what-you-can-and-cannot-do
...which appears as Matt’s ‘Page not found’ page.

**Comment by dracos** [comment]
Yes, whoops, was trying to get the text to wrap better in Chrome but changed the actual links as well as the text! Fixed now, thanks.
