### ISSUE TITLE
FYI: Alderney & Sark won't necessarily follow Guernsey's lead

### ISSUE THREAD

**Issue by IgnoredAmbience** [dracos/local-lockdown-lookup#4]
The States of Alderney (GY9) have stated that whilst they'll broadly follow Guernsey's lead, they might not be fully in sync with them when moving between risk levels. Alderney have already delayed on relaxing previous restrictions, and had more stringent restrictions at the height of the pandemic. Latest press release: http://alderney.gov.gg/article/178610/Press-Release---Covid---Phase-5c-17092020

Sark (GY10), Sark haven't explicity stated this, but they also have the freedom to decide action independently of Guernsey. Most detail on the gov homepage: https://sarkgov.co.uk/

**Comment by dracos** [comment]
Thanks for the extra details; but at present, having read your links, what is on the site is okay and correct (apart from I didn't mention Sark which I've now added)? If it changes in future, I'm happy to provide different guidance for GY9 and GY10.
