### ISSUE TITLE
School opening times are displayed UK-wide, but don't apply in Scotland

### ISSUE THREAD

**Issue by pozorvlak** [dracos/local-lockdown-lookup#6]
If I look up an address in Edinburgh, I see

> Primary schools are reopening as normal on 4th January. Secondary schools will be face to face from 4th January for vulnerable children and the children of critical workers, 11th January also for exam years, and 18th January for all years.

I believe these are correct for England, but school term dates are different in Scotland. The [most recent information I can find on the Edinburgh Council website](https://www.edinburgh.gov.uk/schools-learning/returning-school-august-2020/2?documentId=12983&categoryId=20014) (updated 2020-12-22) says schools will be open for children of key workers from 6th Jan, online learning will begin for other children from 11th Jan, and all children (including primary school children) will return to school from 18th Jan. Dates for [Glasgow](https://glasgow.gov.uk/article/17024/School-Term-Dates) and [Dundee](https://www.dundeecity.gov.uk/news/article?article_ref=3821) appear to be similar, but with the "key workers only" period starting on the 7th. Usually [Scottish local authorities set their own term dates](https://education.gov.scot/parentzone/my-school/general-school-information/term-dates/), but I think the 11th Jan and 18th Jan dates are part of the Scottish government's coronavirus restrictions so will apply Scotland-wide (unless they change, which they might well do soon).

**Comment by dracos** [comment]
Thanks, idiot me, fixed (set to be England only) by https://github.com/dracos/local-lockdown-lookup/commit/eaa41611e9680bae26d12507cfecbe5ce3bafc5b
